// /scripts/seed/templates/bios.ts

// Bio templates per archetype.
// Placeholders:
// {year} → year between 2018-2025
// {count} → number between 50-500
// {fav_title} → popular manhwa title

export const BIO_TEMPLATES: Record<string, string[]> = {
  ACTION_JUNKIE: [
    "Solo Leveling got me into manhwa. Now I can't stop. ⚔️",
    'Action manhwa > everything else. Fight me.',
    "If it has dungeons and leveling, I'm reading it.",
    'Reading manhwa since {year}. Mostly action and fantasy.',
    "Fan de manhwa d'action depuis {year}. Mon top 1 : {fav_title}.",
    "{fav_title} m'a fait découvrir les manhwa. Depuis je suis accro.",
    'Cherche toujours le prochain Solo Leveling. Suggestions bienvenues.',
    'OP MC enjoyer 💪',
    "I've read over {count} manhwas. My favorites are all action.",
    'Murim and dungeons are my thing.',
    'If it has a system and OP MC, sold.',
    'Gates, dungeons, tower climbing — bring it all.',
    'Fantasy manhwa collector since {year}.',
    'My TBR list has {count} action manhwas and counting.',
    'Power fantasy fan. Not apologizing.',
    'Je note 9/10 si le MC devient OP assez vite.',
    'Addict au fantasy manhwa coréen.',
    "Hunter rankings and guild wars are my aesthetic.",
    "I've been burned by too many manhwas that went on hiatus. Still reading though.",
    'Action > romance. Always.',
  ],
  ROMANCE_READER: [
    'Je lis surtout des romances et des slice of life 🌸',
    'Romance manhwa addict. No shame.',
    "If it makes me cry, it's a 10/10.",
    'Ici pour les histoires d\'amour et les feels.',
    'Reading romance manhwa at 3am is a lifestyle.',
    'Mon guilty pleasure : les romances isekai.',
    'Webtoon romance >> everything',
    'I rate based on how much it makes me feel.',
    'Fan de drama et romance depuis {year}.',
    'Les manhwa romance coréens sont supérieurs, point.',
    'Enemies to lovers is my love language.',
    'Give me slow burn or give me nothing.',
    'My heart has been broken by too many manhwa couples.',
    'I come for the romance, I stay for the art.',
    'Historical romance manhwa are criminally underrated.',
    'Je pleure à chaque chapitre depuis {year}.',
    'Found my favorite manhwa in {year} and still not over it.',
    'Drama and romance reader looking for recs 🌸',
    'Villainess stories are just romance with extra steps.',
    'I track my reads here. Mostly romance. Mostly crying.',
  ],
  MURIM_ENTHUSIAST: [
    'Murim manhwa is peak fiction.',
    "If it has martial arts and cultivation, I'm in.",
    'Return of the Mount Hua Sect is GOAT.',
    'Murim > Dungeons. I said what I said.',
    "Reading murim manhwa since before it was cool.",
    'Internal energy goes brrrr',
    'Fan de murim depuis {year}. Plus de {count} titres lus.',
    'Mount Hua Sect fanboy',
    'Martial arts manhwa connoisseur',
    'The way of the sword is the only way.',
    'Regression murim stories hit different.',
    'I can tell good murim from bad murim in 5 chapters.',
    'Qi deviation and sword intent are my aesthetics.',
    "If the MC doesn't train 100x harder than his rivals, dropping.",
    'Murim addict since {year}. No cure in sight.',
    'Arts martiaux et cultivation depuis {year}.',
    'Wuxia manhwa enjoyer. The Chinese stuff too.',
    'Old man protagonist murim > young genius murim.',
    'I read everything that comes out in the murim genre.',
    'Tang Sect and Mount Hua — GOAT sects.',
  ],
  CRITICAL_REVIEWER: [
    "I rate honestly. Don't expect 10/10s from me.",
    'Quality over hype. Always.',
    'Reviewing manhwa seriously since {year}.',
    'If the writing is lazy, the score will reflect it.',
    'Je note sévèrement mais justement.',
    'Art is 30%, story is 50%, characters are 20%.',
    'I appreciate good storytelling above all.',
    "Not here to agree with the crowd.",
    'Harsh but fair reviewer.',
    "If I gave it above 7, it's genuinely good.",
    'My average score is 6.2. Yes I know.',
    'Been reading manhwa since {year}. I\'ve seen it all.',
    'I have {count} manhwas in my completed list. I have opinions.',
    'Overhyped ≠ good. My reviews explain why.',
    'I read manhwa critically. If that bothers you, good.',
    'Long reviews are my thing. Short takes are lazy.',
    'My 10s are sacred. My 1s are earned.',
    'The plot holes in popular manhwas drive me insane.',
    'Former lit student. It shows in my reviews.',
    "If you want validation, don't read my reviews.",
  ],
  CASUAL_READER: [
    'I read a bit of everything 📚',
    'Je lis des manhwa quand j\'ai le temps.',
    'Casual reader, big enjoyer.',
    'Here to track what I read.',
    'Manhwa newbie, learning the ropes.',
    'Started reading manhwa recently. Loving it so far!',
    'Je découvre les manhwa, c\'est super !',
    'Random reader, random tastes.',
    'No particular genre preference, I just like good stories.',
    'Nouveau ici, je cherche des recommandations !',
    'Started with {fav_title} and haven\'t stopped since.',
    'Just here to keep track of my reading.',
    "I read whatever is popular. No shame.",
    'Casual enjoyer, occasional reviewer.',
    'Life is too short to read bad manhwa, but I do it anyway.',
    'Je lis ce qui me passe sous la main.',
    'Discovered manhwa in {year}, no regrets.',
    'My reading speed: whenever I can.',
    "Looking for good stories. Genre doesn't matter much.",
    'Read {count} manhwas, enjoyed most of them.',
  ],
  BINGE_READER: [
    'I read 10+ chapters a day. Send help.',
    '{count}+ manhwas read and counting.',
    "Sleep is for people who've caught up on their reading list.",
    'Ma bibliothèque est plus grande que mon appartement.',
    "I don't read manhwa, manhwa reads me.",
    'Binge reading is a sport and I\'m an athlete.',
    "If it's completed, I'm reading it in one sitting.",
    'Speed reader extraordinaire.',
    "J'ai lu plus de {count} manhwa. Oui, j'ai un problème.",
    'My reading list never gets shorter.',
    'Started in {year}, read {count}+ since then. Send help.',
    "I've read more manhwa than I've slept hours this year.",
    'Weekend plans: binge {fav_title} from start to finish.',
    'If I start a manhwa, I finish it. Same day usually.',
    'TBR list: {count} and growing. It won\'t get smaller.',
    'Je lis vite, je note rarement, j\'en lis d\'autres.',
    'Hiatus manhwas are my arch-nemesis.',
    'Completed only. Ongoing manhwas stress me out.',
    'My productivity died in {year} when I found webtoons.',
    'Read everything by my favorite authors. Multiple times.',
  ],
  MANHUA_SPECIALIST: [
    'Manhua appreciation post.',
    'Chinese comics need more love.',
    'Cultivation manhua > everything',
    'I read mostly manhua. Sue me.',
    'Fan de manhua depuis {year}. La Chine produit des pépites.',
    'Manhua cultivation enjoyer',
    'My heart is with manhua.',
    'The manhua art style hits different.',
    'Spécialiste manhua, mais je lis aussi des manhwa.',
    'Donghua and manhua, that\'s my world.',
    'Top-tier manhua are slept on criminally.',
    "If it's cultivation or xianxia, I've probably read it.",
    'Chinese webcomics have the best power systems.',
    'Reading manhua since {year}. Never going back.',
    'Manhua → manhwa → back to manhua. It\'s a cycle.',
    'Les fans de manhua sont trop rares. Je vous trouve.',
    'Battle through the heavens era veteran.',
    'I read MTL when the official translation is too slow.',
    'Manhua has the best art when it\'s good.',
    'Spreading manhua appreciation one review at a time.',
  ],
}

// Popular manhwa titles used for {fav_title} placeholder
export const POPULAR_TITLES = [
  'Solo Leveling',
  'Tower of God',
  'The Beginning After the End',
  'Omniscient Reader',
  'Return of the Mount Hua Sect',
  'Nano Machine',
  'Martial Peak',
  'Lookism',
  'True Beauty',
  'I Love Yoo',
  'Under the Oak Tree',
  'Remarried Empress',
  'Lady Baby',
  'Doctor Elise',
  'The Boxer',
  'Weak Hero',
  'Kill the Hero',
  'I Shall Master This Family',
]
