// /scripts/seed/templates/reviews-micro-en.ts
// Quick reviews EN (1-2 sentences) by score range
// Placeholders: {title}, {genre}, {chapters}, {drop_chapter}

export const MICRO_REVIEWS_EN: Record<'high' | 'mid' | 'low', string[]> = {
  // Score 8-10: enthusiastic
  high: [
    'Absolute masterpiece. Binged all {chapters} chapters in one sitting.',
    "Best {genre} manhwa I've ever read. Period.",
    "If you haven't read {title}, what are you doing with your life?",
    '10/10. The art is gorgeous and the story is flawless.',
    'My favorite manhwa of all time. Will definitely reread.',
    'The story is insane, characters are lovable, art is stunning. Perfect.',
    'I cried, I laughed, I screamed. Peak fiction right here.',
    'The kind of manhwa that keeps you up until 4am.',
    'Every chapter hits different. Impossible to put down.',
    'I finally get the hype. It really is that good.',
    'Best {genre} manhwa. By far.',
    'Peak. No other words needed.',
    "I'd recommend this to anyone. Even non-{genre} fans will love it.",
    'Post-manhwa depression hits hard with this one.',
    'The author is a genius. Every plot twist is perfect.',
    'Top 3 all time for me. Characters are incredibly well written.',
    'Read the whole thing in one go. Couldn\'t stop.',
    'Wish I could erase my memory and read it again.',
    '대박. Just... 대박.',
    'This is what manhwa is supposed to be.',
    'A masterpiece that exceeded every expectation I had.',
    'Every arc is better than the last. Incredible consistency.',
    'The art alone is worth it. The story makes it GOAT tier.',
    'Read it twice. Will read it a third time.',
    "The MC is iconic. One of the best protagonists I've seen in the genre.",
    'Objectively top tier. I recommend it with my eyes closed.',
    'Stayed up all night to finish. Have a meeting in the morning. No regrets.',
    'The world-building is insane. You get lost in it in the best way.',
    'Rare to find a manhwa this consistent from chapter 1 to the end.',
    'Top {genre}, no question. Others can go home.',
    'This manhwa got me addicted to {genre}. Thanks and sorry about my sleep.',
    'I tell everyone about it. They\'re tired of hearing it. Don\'t care.',
    'The fights are a masterclass. Every panel slaps.',
    'The ending left me speechless. Rarely seen that done so well.',
    'If I had to recommend one manhwa, this would be it.',
    'Secondary characters are as well developed as the MC. Exceptional.',
    'Went back and reread from the start after finishing. That good.',
    "You can feel the author's passion in every chapter.",
    'One of the rare manhwas where I didn\'t skip a single panel.',
    'The hype is 100% deserved. Rare to say that.',
    'Just go read it. That\'s all.',
    'The MC glow-up is the most satisfying I\'ve ever seen.',
    'Beautiful art + deep story + memorable characters = masterpiece.',
    'Switches from comedy to tears without warning. Narrative genius.',
    'This manhwa will stick with me for a long time.',
    'Even the antagonists are well written. So rare.',
    'Finished and already feeling the void. Someone help.',
    'The atmosphere is unique. No other manhwa feels like this.',
    'Wish I could discover it again for the first time.',
    '5 stars. 10/10. No identifiable flaws.',
  ],

  // Score 6-7: positive but nuanced
  mid: [
    'Pretty good. Some pacing issues but overall excellent.',
    'Solid. Beautiful art and the story holds up well.',
    'I liked it! Not perfect but recommended.',
    "Pleasant surprise, didn't expect to get hooked like this.",
    'A good {genre} manhwa. Not groundbreaking but enjoyable.',
    'Story is engaging even if the ending feels rushed.',
    'Recommended for {genre} fans. You\'ll have a good time.',
    'Characters are the highlight. Story is decent.',
    'Gorgeous art, somewhat generic plot but well executed.',
    'Nice read. MC is likable.',
    'Not bad at all. Easy to binge.',
    'Good entertainment. Nothing exceptional but fun.',
    'Enjoyed all {chapters} chapters.',
    'Slow start but worth sticking with.',
    'Recommended for {genre} fans. Others, maybe.',
    'Cool world-building. Enjoyed it.',
    'Wish some arcs were more developed, but still good.',
    'Good read. Adding to my recommendations.',
    'Perfect for killing time. Solid 7-8 territory.',
    "It's good. Not the best but clearly above average.",
    'The art compensates for the weaker story elements.',
    'An honest 7/10. Does what it sets out to do.',
    'Some arcs are weaker but the overall package is solid.',
    'Good time even if it\'s not my favorite genre.',
    'MC is a bit generic but the story carries it.',
    "I'd recommend this to someone new to the {genre} genre.",
    'The humor lands well. Serious moments too.',
    'Well paced, readable in one go. Not memorable but pleasant.',
    'Fights are well choreographed even if the plot is basic.',
    'Good for unwinding. Nothing too complex.',
    'The setting has potential even if not fully explored.',
    'Highs and lows but the trend is positive.',
    "Would've given it an 8 if the ending was better written.",
    'Enjoyable without being exceptional. Exactly what I expected.',
    'Nice. Glad I read it.',
    'Side characters are often more interesting than the MC.',
    'A bit generic but crafted with care. Worth reading.',
    'Easy and enjoyable read. Good for chill sessions.',
    'Art style is really well done even if the story is standard.',
    "I'd come back for more chapters. Good manhwa overall.",
    'Missing that one thing to push it to the next level.',
    'A solid 7. Not exceptional, not disappointing.',
    'The potential is there. The execution is good enough.',
    'One of the better mid-tier manhwas. I recommend it.',
    'Honestly more enjoyable than I expected.',
    "The side romance is better written than the main plot.",
    'Pleasant to read, easy to forget, but still worthwhile.',
    'Decent read. Some genuinely good moments.',
    'Better than average, not as good as the greats.',
    'A good reading experience overall.',
  ],

  // Score 1-5: disappointed/critical
  low: [
    'Meh. Good concept, poor execution.',
    "It's mid. Readable but forgettable.",
    'Art is fine but the story is generic.',
    'Dropped at chapter {drop_chapter}. Too repetitive.',
    'Disappointing given the hype. It\'s just... okay.',
    'MC is unbearable. The rest is passable.',
    'Had potential but it\'s wasted.',
    'Too many clichés. Feels like every other manhwa.',
    'Art saves it somewhat but the story is weak.',
    "I don't understand the high ratings. It's really mid.",
    "There's so much better in the same genre.",
    'Started promising but derailed after chapter {drop_chapter}.',
    'Generic. OP MC with no development, forgettable villains.',
    'Author clearly ran out of ideas halfway through.',
    'Not great. Pacing is too slow.',
    'Finished it out of obligation, not enjoyment.',
    'Cool concept, bad execution.',
    "Meh. Read it when there's nothing else.",
    'Honestly disappointing. Expected more.',
    'Too much filler. Could\'ve been half the chapters.',
    'Dropped at chapter {drop_chapter}. Motivation died.',
    'The power system is interesting but everything else is hollow.',
    "Wouldn't have read it if I'd known. Not terrible but overhyped.",
    'MC makes such stupid decisions it becomes frustrating.',
    'Zero originality. Copy-paste of other manhwas in the genre.',
    'Art is the only positive. Everything else doesn\'t live up to the praise.',
    'Dropping at chapter {drop_chapter}. Life is too short.',
    'Antagonists are so flat it\'s almost funny.',
    "Too many inconsistencies in the world-building. Hard to stay immersed.",
    '3/10 for art, 4/10 for story. Doesn\'t add up to much.',
    'Hoped for more. The reputation was clearly exaggerated.',
    'Pacing is catastrophic. 30 chapters of nothing happening.',
    'Honestly not recommended. Move on.',
    'The author clearly abandoned the story halfway through.',
    'Potential was there but it all falls apart after arc 2.',
    'I get the appeal but it really doesn\'t live up to the hype.',
    'The plot twist at chapter {drop_chapter} killed all my interest.',
    'Frustrating. You can see what it could\'ve been and it\'s not that.',
    'Hollow characters in an empty world. Hard to finish.',
    'Less good than the reviews suggest. Pretty bland.',
    'Read to the end out of principle. Avoid.',
    'Too repetitive to be engaging. Same formula every arc.',
    'Enjoyable for the first 20 chapters, then it drops off.',
    'Worst {genre} I\'ve read this year.',
    '2 stars for the artistic effort. The rest is worthless.',
    'Disappointed. Waited a while for this and that\'s it?',
    'Too slow, too predictable, too generic.',
    'Skip if you have better options in the genre.',
    'Hope the author improves on the next project.',
    'A promising concept ruined by sloppy execution.',
  ],
}
