// /scripts/seed/templates/reviews-micro-fr.ts
// Avis rapides FR (1-2 phrases) classés par range de score
// Placeholders: {title}, {genre}, {chapters}, {drop_chapter}

export const MICRO_REVIEWS_FR: Record<'high' | 'mid' | 'low', string[]> = {
  // Score 8-10 : enthousiaste
  high: [
    "Chef-d'œuvre absolu. J'ai dévoré les {chapters} chapitres en 2 jours.",
    'Incroyable du début à la fin. Le meilleur {genre} que j\'ai lu.',
    "Si tu n'as pas lu {title}, tu rates quelque chose.",
    "10/10 sans hésitation. L'art est magnifique et l'histoire est parfaite.",
    'Mon manhwa préféré de tous les temps. Je le relirai c\'est sûr.',
    "L'histoire est folle, les persos sont attachants, l'art est sublime. Que demander de plus ?",
    "J'ai pleuré, j'ai ri, j'ai crié. Masterpiece.",
    "Le genre de manhwa qui te fait rester éveillé jusqu'à 4h du mat'.",
    "Chaque chapitre est une claque. Impossible de s'arrêter.",
    'Je comprends le hype maintenant. C\'est vraiment aussi bien qu\'on le dit.',
    'Le meilleur manhwa de {genre}. De loin.',
    'Peak fiction. Pas d\'autres mots.',
    'Je recommande à 100%. Même les non-fans de {genre} vont kiffer.',
    "Quand t'as fini tu te sens vide tellement c'est bien.",
    "L'auteur est un génie. Chaque plot twist est parfait.",
    'Mon top 3 all time. Les persos sont incroyablement bien écrits.',
    "J'ai tout lu d'une traite. Impossible de lâcher.",
    'Si je pouvais effacer ma mémoire pour le relire... 😭',
    '대박 ! Juste... 대박.',
    'Le type de manhwa pour lequel on oublie de dormir.',
    "Un chef-d'œuvre que j'attendais sans le savoir.",
    "Chaque arc est meilleur que le précédent. C'est impressionnant.",
    "L'art de ce manhwa est à couper le souffle. Chaque panneau est soigné.",
    "Relu deux fois. Je le relirai encore.",
    "Le MC est iconique. Un des meilleurs protagonistes que j'ai vus.",
    "Je recommande les yeux fermés. Objectivement top tier.",
    "Binged en une nuit. J'ai une réunion demain matin. Aucun regret.",
    "Le world-building est insensé. On se perd dedans de la meilleure façon.",
    "Rare de trouver un manhwa aussi cohérent du chapitre 1 à la fin.",
    "Top {genre} sans question. Les autres peuvent rentrer chez eux.",
    "Ce manhwa m'a rendu accro aux {genre}. Merci et désolé pour mon sommeil.",
    "J'en parle à tout le monde autour de moi. Ils en ont marre mais tant pis.",
    "Les combats sont une masterclass. Chaque panel est de la bombe.",
    "L'ending m'a laissé sans voix. Rarement vu ça.",
    "Si je devais recommander un seul manhwa, ce serait celui-là.",
    "Le développement des personnages secondaires est aussi soigné que le MC.",
    "Tellement bon que j'ai relu depuis le début après la fin.",
    "On voit la passion de l'auteur à chaque chapitre.",
    "Un des rares manhwa où je n'ai pas skippé une seule case.",
    "La hype est 100% méritée. Rare de dire ça.",
    "Foncez. C'est tout ce que j'ai à dire.",
    "Le MC glow-up est le plus satisfaisant que j'aie jamais vu.",
    "Art magnifique + histoire profonde + personnages mémorables = masterpiece.",
    "On passe du rire aux larmes sans prévenir. Génie narratif.",
    "Un manhwa qui restera dans ma tête encore longtemps.",
    "Même les antagonistes sont bien écrits. C'est tellement rare.",
    "Terminé et je ressens déjà le vide. Quelqu'un pour m'aider ?",
    "L'atmosphère est unique. Aucun autre manhwa ne donne cette sensation.",
    "J'aurais aimé le découvrir aujourd'hui pour le lire pour la première fois.",
    "5 étoiles. 10/10. Aucun défaut identifiable.",
  ],

  // Score 6-7 : positif
  mid: [
    'Très bon manhwa. Quelques longueurs mais globalement excellent.',
    "Solide. L'art est vraiment beau et l'histoire tient la route.",
    "J'ai bien aimé ! Pas parfait mais recommandé.",
    "Bonne surprise, je m'attendais pas à accrocher autant.",
    'Un bon {genre}. Pas révolutionnaire mais très plaisant à lire.',
    "L'histoire est prenante même si la fin est un peu rapide.",
    'Je recommande si vous aimez le {genre}. Vous passerez un bon moment.',
    "Les personnages sont le point fort. L'histoire est correcte.",
    'Art magnifique, scénario un peu classique mais bien exécuté.',
    'Agréable à lire. Le MC est attachant.',
    'Pas mal du tout. Ça se lit facilement.',
    'Un bon divertissement. Rien d\'exceptionnel mais c\'est fun.',
    'J\'ai lu les {chapters} chapitres avec plaisir.',
    'Le début est lent mais ça vaut le coup de persévérer.',
    'Recommandé aux fans de {genre}. Les autres, ça dépend.',
    "Sympa ! L'univers est bien construit.",
    "J'aurais aimé que certains arcs soient plus développés, mais c'est bien.",
    'Bon moment de lecture. Je mets dans mes recommandations.',
    'Le genre de manhwa parfait pour passer le temps.',
    "Honnêtement c'est bien. Pas le meilleur mais clairement au-dessus de la moyenne.",
    "L'art compense largement les faiblesses du scénario.",
    "Un 7/10 honnête. Fait bien ce qu'il fait.",
    "Quelques arcs en dessous du reste mais l'ensemble est solide.",
    "J'ai passé un bon moment même si c'est pas mon genre favori.",
    "Le MC est un peu fade mais l'histoire porte le tout.",
    "Je le recommanderais à quelqu'un qui débute dans le {genre}.",
    "L'humour fonctionne bien. Les moments sérieux aussi.",
    "Bien rythmé, lisible d'une traite. Pas mémorable mais plaisant.",
    "Les combats sont bien chorégraphiés même si l'histoire est basique.",
    "Bon manga pour se détendre. Pas de prise de tête.",
    "L'univers a du potentiel même si tout n'est pas exploité.",
    "Des hauts et des bas mais la courbe est positive.",
    "J'aurais mis 8 si la fin était mieux écrite.",
    "Agréable sans être exceptionnel. Exactement ce que j'attendais.",
    "Sympathique. Je suis content de l'avoir lu.",
    "Les personnages secondaires sont souvent plus intéressants que le MC.",
    "Un peu générique mais exécuté avec soin. Vaut le détour.",
    "Lecture facile et plaisante. Bon pour les moments de détente.",
    "Le style artistique est vraiment réussi même si l'histoire est classique.",
    "Je reviendrais lire la suite. Bon manhwa dans l'ensemble.",
    "Il manque un petit quelque chose pour passer au niveau supérieur.",
    "Un bon 7. Ni exceptionnel ni décevant.",
    "Le potentiel est là. L'exécution est correcte.",
    "Un des meilleurs manhwa dans le mid-tier. Je recommande.",
    "Honnêtement plus agréable que je pensais.",
    "La romance secondaire est mieux écrite que l'intrigue principale.",
    "Plaisant à lire, facile à oublier, mais quand même bien.",
    "Lecture correcte. Quelques moments vraiment bien.",
    "Mieux que la moyenne, pas aussi bon que les grands.",
    "Une bonne expérience de lecture dans l'ensemble.",
  ],

  // Score 1-5 : mitigé/négatif
  low: [
    "Bof. Le concept est bien mais l'exécution laisse à désirer.",
    "C'est moyen. Ça se lit mais ça s'oublie vite.",
    "L'art est correct mais l'histoire est générique.",
    "J'ai abandonné au chapitre {drop_chapter}. Trop répétitif.",
    'Décevant par rapport au hype. C\'est juste... ok.',
    "Le MC est insupportable. Le reste est passable.",
    "Ça avait du potentiel mais c'est mal exploité.",
    'Trop de clichés. On a l\'impression de lire le même manhwa qu\'avant.',
    "L'art sauve un peu le tout mais le scénario est faible.",
    'Je comprends pas les notes élevées. C\'est vraiment moyen.',
    "Passable. Y'a tellement mieux dans le même genre.",
    "Le début promettait mais ça part en vrille après le chapitre {drop_chapter}.",
    'Générique. MC OP sans développement, vilains oubliables.',
    "L'auteur avait clairement plus d'idées à partir du milieu.",
    'Pas terrible. Le rythme est trop lent.',
    "J'ai fini par obligation mais sans plaisir.",
    "Le concept est cool, l'exécution est ratée.",
    "Meh. Ça se lit quand y'a rien d'autre.",
    "Honnêtement décevant. J'attendais mieux.",
    "Trop de remplissage. L'histoire aurait pu tenir en moitié moins de chapitres.",
    "Abandonné au {drop_chapter}e chapitre. La motivation est morte.",
    "Le power system est intéressant mais tout le reste est vide.",
    "J'aurais pas lu si j'avais su. Pas horrible mais clairement surcôté.",
    "Le MC prend des décisions tellement stupides que c'en est frustrant.",
    "Zéro originalité. Du copier-coller d'autres manhwas du genre.",
    "L'art est le seul point positif. Le reste ne mérite pas les éloges.",
    "Dropping au chapitre {drop_chapter}. La vie est trop courte.",
    "Les antagonistes sont tellement plats que c'en est risible.",
    "Trop d'incohérences dans l'univers. Difficile de rester immergé.",
    "3/10 pour l'art, 4/10 pour l'histoire. Ça fait pas le compte.",
    "J'espérais mieux. La réputation était clairement exagérée.",
    "Le rythme est catastrophique. 30 chapitres pour qu'il ne se passe rien.",
    "Honnêtement pas recommandé. Passez votre chemin.",
    "L'auteur a abandonné l'histoire à mi-chemin, clairement.",
    "Le potentiel était là mais tout part en eau de boudin après l'arc 2.",
    "Je comprends l'attrait mais c'est vraiment pas au niveau du hype.",
    "Le tournant narratif du chapitre {drop_chapter} a tué tout mon intérêt.",
    "Frustrant. On voit ce que ça aurait pu être et c'est pas ça.",
    "Des personnages creux dans un univers vide. Difficile à finir.",
    "Moins bon que les reviews le laissent penser. Assez banal.",
    "J'ai lu jusqu'à la fin par principe. À éviter.",
    "Trop répétitif pour être engageant. La même formule à chaque arc.",
    "Agréable les 20 premiers chapitres, puis ça dégringole.",
    "Le pire des {genre} que j'aie lu cette année.",
    "2 étoiles pour l'effort artistique. Le reste ne vaut rien.",
    "Déçu. J'attendais depuis longtemps et c'est tout ?",
    "Trop lent, trop prévisible, trop générique.",
    "À fuir si vous avez de meilleures options dans le genre.",
    "J'espère que l'auteur rebondit sur son prochain projet.",
    "Un concept prometteur gâché par une exécution bâclée.",
  ],
}
